### ISSUE TITLE
Doesn't seem to work for https://www.theglobeandmail.com/

### ISSUE THREAD

**Issue by tenf00t** [rushilsrivastava/OpenNews#1]
Installed from the chrome extension store
Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by rushilsrivastava** [comment]
Hm, let me give check this out. Are you using OpenNews with any other extension?

**Comment by rushilsrivastava** [comment]
Seems the path was updated. I have changed the source. Will push update to Chrome Webstore soon. Thanks for reporting this!
