### ISSUE TITLE
WSJ Paywall

### ISSUE THREAD

**Issue by rourpab** [rushilsrivastava/OpenNews#10]
- [Wall Street Journal](https://www.nytimes.com/)

- Paywall appears on some articles, although if you reload some articles X number of times the paywall sometimes disappears.

- https://www.wsj.com/articles/u-s-government-still-uses-suspect-chinese-cameras-11571486400

**Comment by rushilsrivastava** [comment]
Thanks for sharing, I think the core of the problem is that the `?mod=rssn` is loading too slowly. Investigating this.

**Comment by rourpab** [comment]
> Thanks for sharing, I think the core of the problem is that the `?mod=rssn` is loading too slowly. Investigating this.

Changing user agent with Googlebot fixes the problem according to another repo

**Comment by rushilsrivastava** [comment]
Thanks for the update, I am working on a rewrite that will allow for us to individually choose the headers for each site based on a config. Sorry for the delay!

**Comment by rushilsrivastava** [comment]
@rourpab It looks like this issue has resolved itself, the update is taking longer than I anticipated, but I just tested WSJ and it looks like it is working from my end. Can you confirm?

**Comment by rushilsrivastava** [comment]
9f21706 fixes this using Googlebot, thanks for reporting and sorry for the delay @rourpab!
