### ISSUE TITLE
This is obviously a rip off of Bypass Paywalls without any credit.

### ISSUE THREAD

**Issue by iamadamdev** [rushilsrivastava/OpenNews#12]
You even copied my README file.

**Comment by rushilsrivastava** [comment]
Lol, I took the readme after you took my commit for adding autoupdates. Go check your own commit logs and compare mine. The code is completely different, more efficient, and cleaner.

**Comment by rushilsrivastava** [comment]
Let's clarify your baseless allegations: My code is unique, cleaner, and more efficient. No part of this has been copied, my README file is also independent and at best inspired yours. My project has also been around almost as long as yours. Stop whining, there is nothing I need to credit here.

**Comment by iamadamdev** [comment]
Uhm, you obviously copied my README.

**Comment by rushilsrivastava** [comment]
Clearly you have went a bit unhinged. It looks like the maintainers of your own repo agree with me too and have opened their [own repo](https://github.com/magnolia1234/bypass-paywalls-chrome-clean). Look forward to working with them in the future.
