### ISSUE TITLE
Not working on FT.com

### ISSUE THREAD

**Issue by VeryNaughtyCat** [rushilsrivastava/OpenNews#2]
Hi,  was working earlier on FT.com but not anymore.

**Comment by rushilsrivastava** [comment]
Hi, thanks for reporting. Will take a look at this today.

**Comment by rushilsrivastava** [comment]
My tests show that it is still working. Could you provide an example on where it isn't working, and confirm that this is a problem caused by OpenNews by disabling all other extensions?

I have found that the integration isn't as smooth though, I will take a look into that for the time being.

**Comment by rushilsrivastava** [comment]
I have updated the extension to v0.19, try that version and let me know if you still have any issues. From my testing though, this was working in v0.18.1 as well.

**Comment by VeryNaughtyCat** [comment]
Hi
Thanks for that - all working well now.

**Comment by rushilsrivastava** [comment]
Great, glad to hear it.
