### ISSUE TITLE
New Site: Business Insider

### ISSUE THREAD

**Issue by chrisgo** [rushilsrivastava/OpenNews#7]
https://www.businessinsider.com/google-emails-adtrader-lawsuit-refund-ad-click-fraud-2019-5

Thanks!

**Comment by rushilsrivastava** [comment]
One immediate solution to Business Insider is to disable the javascript. However, this removes the article picture and other features on the site. I think there may be a cleaner solution, but for the time being that is a good work around.

**Comment by rushilsrivastava** [comment]
Upon further inspection it looks like they are using a service called TinyPass. 
I have added this in 4811aca and will release a new version soon.

**Comment by rushilsrivastava** [comment]
Version 0.19.3 includes Business Insider and can be found [here](https://github.com/rushilsrivastava/OpenNews/releases/tag/v0.19.3) (also available by updating extension)
