### ISSUE TITLE
NYT Paywall

### ISSUE THREAD

**Issue by rourpab** [rushilsrivastava/OpenNews#9]
- [New York Times](https://www.nytimes.com/)

- Paywall appears after a certain number of articles

- https://www.nytimes.com/2019/10/19/business/economy/workers-strike-economy.html

**Comment by rushilsrivastava** [comment]
Thanks for reporting. Will look into this soon, I wonder if they have changed their JS engine.

**Comment by rourpab** [comment]
> Thanks for reporting. Will look into this soon, I wonder if they have changed their JS engine.

Looks like the ?mod=rsswn method was patched directly or indirectly..
I noticed some other devs tinkering with Google Bot as a user agent to bypass WSJ, NYT etc., could be possible to integrate it here

**Comment by rushilsrivastava** [comment]
8b87467 fixes this problem.
